#! /usr/bin/bash

# update vcstool
python -m pip install git+https://github.com/voshch/vcstool.git || echo 'failed vcstool upgrade, ignoring'

export ROSDEP_EXCLUDES='libignition-gazebo6-dev gazebo_dev gazebo_ros gazebo_plugins gazebo_ros2_control'

WARN='\033[0;93m'
WHITE='\033[0;37m'
GREEN='\033[0;32m'
RED='\033[0;31m'
RESET='\033[0m'

FATAL=0

run(){
    tst='$(('${2:-'$?'}'))'
    if [ $FATAL -eq 0 ]; then
        (eval $1)
        (exit $(eval echo $tst))
        FATAL=$?
    fi
}

run '(cd src/arena/arena-rosnav && git pull --ff-only --autostash || true);'
run '(vcs import --input src/arena/arena-rosnav/arena.repos --recursive --ff --add-existing src);' '$? > 1'


if [ -f src/arena/arena-rosnav/.installed ] ; then
    while read -r installed; do 
        name="$(echo $installed | cut -d. -f1)"
        if [ -f "src/arena/arena-rosnav/.repos/${name}.repos" ] ; then
            run "(vcs import --input src/arena/arena-rosnav/.repos/${name}.repos --recursive --ff --add-existing src);" '$? > 1'
        fi
    done < src/arena/arena-rosnav/.installed
fi
run '(rosdep update --rosdistro "${ARENA_ROS_DISTRO:-humble}" && rosdep install --from-paths src --ignore-src -r -y --skip-keys "${ROSDEP_EXCLUDES}" || echo "rosdep failed to install all dependencies");' 
run '(. src/arena/arena-rosnav/tools/poetry_install);'


if [ $FATAL -ne 0 ] ;
then
    echo -e $RED
    echo 'encountered fatal error while updating'
else
    echo -e $GREEN
    echo 'updated successfully'
    echo -e $RED
    echo "don't forget to rebuild!"
fi

echo -e $RESET