stages:
- config:
    SCENARIO:
      file: 1.json
  episodes: 1
  map: arena_hospital_small
  name: arena_hospital_small_1_jackal
  robot: jackal
  tm_obstacles: scenario
  tm_robots: scenario
- config:
    SCENARIO:
      file: 2.json
  episodes: 1
  map: arena_hospital_small
  name: arena_hospital_small_2_jackal
  robot: jackal
  tm_obstacles: scenario
  tm_robots: scenario
- config:
    SCENARIO:
      file: 3.json
  episodes: 1
  map: arena_hospital_small
  name: arena_hospital_small_3_jackal
  robot: jackal
  tm_obstacles: scenario
  tm_robots: scenario
- config:
    SCENARIO:
      file: 4.json
  episodes: 1
  map: arena_hospital_small
  name: arena_hospital_small_4_jackal
  robot: jackal
  tm_obstacles: scenario
  tm_robots: scenario
- config:
    SCENARIO:
      file: 5.json
  episodes: 1
  map: arena_hospital_small
  name: arena_hospital_small_5_jackal
  robot: jackal
  tm_obstacles: scenario
  tm_robots: scenario
- config:
    RANDOM:
      dynamic:
        max: 5
        min: 3
        models:
        - actor1
      interactive:
        max: 0
        min: 0
        models:
        - shelf
      static:
        max: 10
        min: 5
        models:
        - shelf
    SCENARIO:
      file: 1.json
  episodes: 5
  map: arena_hospital_small
  name: arena_hospital_small_random_jackal
  robot: jackal
  tm_obstacles: random
  tm_robots: scenario
- config:
    SCENARIO:
      file: 1.json
  episodes: 1
  map: arena_hospital_small
  name: arena_hospital_small_1_agvota
  robot: agvota
  tm_obstacles: scenario
  tm_robots: scenario
- config:
    SCENARIO:
      file: 2.json
  episodes: 1
  map: arena_hospital_small
  name: arena_hospital_small_2_agvota
  robot: agvota
  tm_obstacles: scenario
  tm_robots: scenario
- config:
    SCENARIO:
      file: 3.json
  episodes: 1
  map: arena_hospital_small
  name: arena_hospital_small_3_agvota
  robot: agvota
  tm_obstacles: scenario
  tm_robots: scenario
- config:
    SCENARIO:
      file: 4.json
  episodes: 1
  map: arena_hospital_small
  name: arena_hospital_small_4_agvota
  robot: agvota
  tm_obstacles: scenario
  tm_robots: scenario
- config:
    SCENARIO:
      file: 5.json
  episodes: 1
  map: arena_hospital_small
  name: arena_hospital_small_5_agvota
  robot: agvota
  tm_obstacles: scenario
  tm_robots: scenario
- config:
    RANDOM:
      dynamic:
        max: 5
        min: 3
        models:
        - actor1
      interactive:
        max: 0
        min: 0
        models:
        - shelf
      static:
        max: 10
        min: 5
        models:
        - shelf
    SCENARIO:
      file: 1.json
  episodes: 5
  map: arena_hospital_small
  name: arena_hospital_small_random_agvota
  robot: agvota
  tm_obstacles: random
  tm_robots: scenario
- config:
    SCENARIO:
      file: 1.json
  episodes: 1
  map: arena_hospital_small
  name: arena_hospital_small_1_cob4
  robot: cob4
  tm_obstacles: scenario
  tm_robots: scenario
- config:
    SCENARIO:
      file: 2.json
  episodes: 1
  map: arena_hospital_small
  name: arena_hospital_small_2_cob4
  robot: cob4
  tm_obstacles: scenario
  tm_robots: scenario
- config:
    SCENARIO:
      file: 3.json
  episodes: 1
  map: arena_hospital_small
  name: arena_hospital_small_3_cob4
  robot: cob4
  tm_obstacles: scenario
  tm_robots: scenario
- config:
    SCENARIO:
      file: 4.json
  episodes: 1
  map: arena_hospital_small
  name: arena_hospital_small_4_cob4
  robot: cob4
  tm_obstacles: scenario
  tm_robots: scenario
- config:
    SCENARIO:
      file: 5.json
  episodes: 1
  map: arena_hospital_small
  name: arena_hospital_small_5_cob4
  robot: cob4
  tm_obstacles: scenario
  tm_robots: scenario
- config:
    RANDOM:
      dynamic:
        max: 5
        min: 3
        models:
        - actor1
      interactive:
        max: 0
        min: 0
        models:
        - shelf
      static:
        max: 10
        min: 5
        models:
        - shelf
    SCENARIO:
      file: 1.json
  episodes: 5
  map: arena_hospital_small
  name: arena_hospital_small_random_cob4
  robot: cob4
  tm_obstacles: random
  tm_robots: scenario
